commit to add o_transer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,30 @@
-#!/usr/bin/env bash
-#Bash script that transfers a file from our client to a server
-if [[ "$#" -lt 3 ]]; then
+# #!/usr/bin/env bash
+# #Bash script that transfers a file from our client to a server
+# if [[ "$#" -lt 3 ]]; then
+#     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# else
+#     scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
+# fi
+#!/bin/env bash
+
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+# Use scp to transfer the file to the user home directory
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ 
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File successfully transferred to $username@$server_ip:~/"
 else
-    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
+    echo "Error: File transfer failed."
 fi
